### ISSUE TITLE
Use external database

### ISSUE THREAD

**Issue by mfonolleda** [alkacon/opencms-docker#12]
Hi, 

We've tried modifiying the docker-compose file in order to connect to an external database (Aws Aurora) instead of using second container. We are able to connect to the database remotely without issues. Unfortunately the docker-compose up command fails with the error:

> org.opencms.main.CmsInitException: Critical error during OpenCms initialization: Unable to initialize connection pool "default". Is the database up and running?

Below is the modified docker-compose file. Maybe you can help us figure out what's wrong:

```
version: '2.2'
services:
   opencms:
        image: alkacon/opencms-docker:11.0.0
        container_name: opencms
        init: true
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - /home/miquel/workspace/openCms11/webapps:/usr/local/tomcat/webapps
        command: ["/root/opencms-run.sh"] 
             - "DB_PASSWD=secretDBpassword" 
             - "DB_HOST=xxxx.cjrk1qmqildl.eu-west-1.rds.amazonaws.com"
             - "DB_USER=root"
```
